# docker-compose.local.yml
version: '3.9'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
    ports:
      - "5433:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RUBY_VERSION=3.2.2
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres:password@db:5432/myapp_development
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ../frontend-react-test
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../frontend-react-test:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  pg-data:

networks:
  app-network:
    driver: bridge
